[bastion]
bastion-host ansible_host=3.125.93.252

[mosquitto]
mosquitto-broker ansible_host=10.0.2.31 ansible_ssh_common_args='-o ProxyCommand="ssh -i ~/.ssh/ssh-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p ubuntu@3.125.93.252"'
